#!/usr/bin/env zsh

#
# Display an error
#
error() {
  echo "error: $1" 1>&2
  exit 1
}

#
# Write the contents of the clipboard to stdout
#
function readCB() {
	os=`uname`
	case $os in
		# Mac OS X
		Darwin*)
			pbpaste;;
		*)
			error "unsupported os $os";;
	esac
}

#
# Write stdin to the clipboard
#
function writeCB() {
	os=`uname`
	case $os in
		# Mac OS X
		Darwin*)
			pbcopy;;
		*)
			error "unsupported os $os";;
	esac
}

case "$1" in
	read)
		readCB;;
	write)
		writeCB;;
	*)
		echo "Usage:"
		echo "  clipboard read"
		echo "  clipboard write"
		echo
		exit 1;;
esac

