#!/usr/bin/env bash

function conTest() {
	if [[ -z $1 ]] || [[ -z $2 ]]; then
		echo "Bad function call"
		exit 1
	fi

	if ping -c 1 -W 1 "$1" &> /dev/null; then
		echo "$2 OK"
	else
		echo "$2 unreachable"
	fi
}

conTest 1.1.1.1 "Cloudflare DNS (IP)"
conTest one.one.one.one "Cloudflare DNS"
conTest google.com "Google"
conTest github.com "Github"
conTest discord.com "Discord"
conTest hypixel.net "Hypixel"
