#!/usr/bin/env zsh
# Select a subdirectory, the parent directory or $HOME
# with fzf and print the selected directory.

EXTRA=""

# Only add $HOME to EXTRA if --no-home is not set
if [[ $@ != *"--no-home"* ]]; then
	EXTRA="${EXTRA}\$HOME\n"
fi

# Only add .. to EXTRA if --no-parent is not set
if [[ $@ != *"--no-parent"* ]]; then
	EXTRA="${EXTRA}..\n"
fi

# Offer the contents of EXTRA and all subdirectories of the working directory up to a depth of 3
OPTIONS="${EXTRA}$(find . -mindepth 1 -maxdepth 3 -type d 2>/dev/null)"

# Filter out all .git and node_modules directories and their subdirectories
OPTIONS=$(print ${OPTIONS} | rg -ve ".*(\.git|node_modules).*")

# Select one with fzf
SELECTED=$(print ${OPTIONS} | fzf)

# Exit if nothing was selected
if [[ -z ${SELECTED} ]]; then
	exit 0
fi

# Check if SELECTED equals to $HOME
if [[ ${SELECTED} = "\$HOME" ]]; then
	# If so, set SELECTED_DIR to $HOME
	SELECTED_DIR="${HOME}"
# Check if SELECTED equals ..
elif [[ ${SELECTED} = ".." ]]; then
	# If so, set SELECTED_DIR to the parent directory of the current directory
	SELECTED_DIR=$(dirname $(pwd -P))
else
	# Else set SELECTED_DIR to the selected directory
	SELECTED_DIR="$(pwd)/${SELECTED}"
fi

# Print the selected directory
echo ${SELECTED_DIR}
