#!/usr/bin/env bash

name=$(basename "$0")

if [ $# -eq 0 ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo "Usage: $name <nix-args>..."
    echo ""
    echo "A wrapper for the nix command to allow unfree packages"
    echo "Allows unfree packages and provides a clean environment."
    echo ""
    echo "Examples:"
    echo "  $name run nixpkgs#hello"
    echo "  $name build nixpkgs#some-package"
    echo "  $name develop"
    exit 1
fi

subcommand="$1"
shift

exec nix shell -s NIXPKGS_ALLOW_UNFREE 1 nixpkgs\#empty --command nix "$subcommand" --impure "$@"
